dist: xenial
addons:
  apt:
    packages:
    - language-pack-pl
notifications:
  email:
    on_success: never
    on_failure: always
script:
- "./scripts/VICHS_Travis.sh $(dirname $(git diff-tree --no-commit-id --name-only
  -r master)).txt"
env:
  global:
    secure: Krxaeu2w1NF/CGyImVr/4+SYlQRHwGdUc6160pNSJwyJLJcqxw89y2Jp2p1osqv/wX0CN/dEg/cYhiRzCtIkX1EreukDA7U8bdItGS4pUcusvROvU51EzqtYoye2iHJMx0zJntCRCwsO3O+yw8j0wbF4UapaYOZ9sAyDvtpLrwl5EDJajD/lCC8Bhdwxrxmaice4S8yCXCOZfMMLx5MdWBKQHx1dLt9oCkaFc9GxMOFwwFez2jge3wWfooDxkBR+dhhjpbEmePCnGAX0/xSbLNlAWJvbWW1vz4oHeFLlAnUAcbxs/5gPf0mozZCuqvxYm+TAwoauncMKUzIueMp0r7Fv9ILiz/jzbUsJ3fGkT0JLppFWSr3uYKVyIBHAS16aEtSxcg6QY6V+Z7W784uRQZddXMvL7v2Jgs2Knxj+SFo6+zpU59ZVESIVsoE0A74f8VpjuKVRbvOhCYJY2MAa+d0ePZtDBLLL+GEcwlzGBQkluL4iCzLd42cZMkC/JGpmImQU7TpTwIYqaOvwdWXXgP72YJoh9UPJCC+PRkWQsjXmFFeTFrboz3ytUbgJo7hZMtXqI3nZ8176zhYmX/bLdcj3hb1/9W0N1KFax23TlYEXR+2AzPtQGnp6L0KDQQiTWbTywrMhPbX3+5oXkSikNxu/d44TNNrG+FqwbW2GVI0=
