version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/vichs_image:latest
    steps:
    - checkout
    - run: ./scripts/VICHS.sh polish_rss_filters.txt
workflows:
  version: 2
  workflow:
    triggers:
    - schedule:
        cron: 55 23 * * 6
        filters:
          branches:
            only:
            - master
    jobs:
      - build:
          context: org-global
