version: 2
jobs:
  build:
    docker:
      - image: polishfiltersteam/vichs_image:2.26.6
    steps:
      - checkout
      - run: |
          export VICHS_MAIN_PATH="$(pwd)"
          VICHS.sh polish_rss_filters.txt
workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          cron: 55 23 * * 6
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: org-global
