name: Portier

on:
  issues:
    types: [labeled]

jobs:
  close:
    if: github.event.label.name == 'zatwierdzone' || github.event.label.name == 'odrzucone' || github.event.label.name == 'pomyłka'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: hawkeye116477/issue-manager-action@v1
        with:
          mode: "close"
          completed-label: "zatwierdzone"
          not-planned-label: |
            odrzucone
            pomyłka
