name: Aktualizacja listy

on: 
  workflow_dispatch: null
  schedule:
    - cron: "55 22 * * 6"

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: polishfiltersteam/sflb_image:3.0.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 994739
          private-key: ${{ secrets.PRIVATE_APP_HELPER_KEY }}
      - env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 "/usr/bin/SFLB.py" polish_rss_filters.txt
