name: Aktualizacja listy

on: workflow_dispatch
#   schedule:
#     - cron: "0 10,14,18 * * *"
jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: polishfiltersteam/sflb_image:3.0.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 "/usr/bin/SFLB.py" polish_rss_filters.txt
