name: Aktualizacja listy

on: workflow_dispatch
#   schedule:
#     - cron: "0 10,14,18 * * *"
jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: polishfiltersteam/vichs_image:2.26.9-2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          VICHS.sh polish_rss_filters.txt
